FROM node:18-alpine

RUN apk add --no-cache aws-cli jq

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .

COPY secrets-load.sh /usr/local/bin/secrets-load.sh
RUN chmod +x /usr/local/bin/secrets-load.sh

ENTRYPOINT ["secrets-load.sh"]
EXPOSE 3001
CMD ["npm", "start"]